### ISSUE TITLE
Laravel 5.5 Class not found

### ISSUE THREAD

**Issue by Tortschi** [mputkowski/Laravel-Localization#32]
Hello,

i test manuell Installation and get this Error:

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'mputkowski\Localization\ServiceProvider' not found

Steps:
1. composer require mputkowski/laravel-localization
2. Add in app.conf the providers + aliases
3. php artisan vendor:publish --provider="mputkowski\Localization\ServiceProvider" 

On Step 3 i get this Error. Can you help me?

Thanks Tortschi

**Comment by mputkowski** [comment]
I can't replicate the issue on a fresh Laravel 5.5 installation.

Could you try this on fresh project? And if you'll be able to create a repository with your code if it fails, it'll be helpful.
